export interface Listing {
  id: string;
  title: string;
  titleAr: string;
  price: number;
  negotiable: boolean;
  category: string;
  wilaya: string;
  city: string;
  condition: "new" | "used";
  description: string;
  descriptionAr: string;
  images: string[];
  sellerId: string;
  sellerName: string;
  sellerAvatar: string;
  sellerPhone: string;
  sellerRating: number;
  sellerReviews: number;
  sellerSince: string;
  postedAt: string;
  views: number;
  isBoosted: boolean;
  isUrgent: boolean;
}

export interface Conversation {
  id: string;
  listingId: string;
  listingTitle: string;
  listingImage: string;
  otherUser: { id: string; name: string; avatar: string };
  lastMessage: string;
  lastMessageTime: string;
  unread: number;
  messages: { id: string; senderId: string; text: string; time: string }[];
}

export const CATEGORIES = [
  { id: "real_estate", icon: "🏠", color: "#16a34a" },
  { id: "vehicles", icon: "🚗", color: "#dc2626" },
  { id: "electronics", icon: "📱", color: "#2563eb" },
  { id: "clothing", icon: "👕", color: "#9333ea" },
  { id: "home_garden", icon: "🛋️", color: "#ea580c" },
  { id: "jobs", icon: "💼", color: "#0891b2" },
  { id: "services", icon: "🔧", color: "#78716c" },
  { id: "animals", icon: "🐾", color: "#65a30d" },
];

export const WILAYAS = [
  "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa",
  "Biskra", "Béchar", "Blida", "Bouira", "Tamanrasset", "Tébessa",
  "Tlemcen", "Tiaret", "Tizi Ouzou", "Alger", "Djelfa", "Jijel",
  "Sétif", "Saïda", "Skikda", "Sidi Bel Abbès", "Annaba", "Guelma",
  "Constantine", "Médéa", "Mostaganem", "M'Sila", "Mascara", "Ouargla",
  "Oran", "El Bayadh", "Illizi", "Bordj Bou Arréridj", "Boumerdès",
  "El Tarf", "Tindouf", "Tissemsilt", "El Oued", "Khenchela",
  "Souk Ahras", "Tipaza", "Mila", "Aïn Defla", "Naâma", "Aïn Témouchent",
  "Ghardaïa", "Relizane",
];

export const LISTINGS: Listing[] = [
  {
    id: "1",
    title: "iPhone 14 Pro 256GB – Excellent état",
    titleAr: "آيفون 14 برو 256 جيغا – حالة ممتازة",
    price: 145000,
    negotiable: true,
    category: "electronics",
    wilaya: "Alger",
    city: "Hydra",
    condition: "used",
    description: "iPhone 14 Pro 256GB Space Black. Utilisé 6 mois, aucune rayure. Vient avec boîte originale, chargeur et coque de protection. Batterie à 96%.",
    descriptionAr: "آيفون 14 برو 256 جيغابايت لون أسود. مستعمل 6 أشهر، بدون خدوش. يأتي مع العلبة الأصلية والشاحن وغطاء الحماية. البطارية 96%.",
    images: [
      "https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=500&q=80",
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=500&q=80",
    ],
    sellerId: "u1",
    sellerName: "Karim Benali",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Karim",
    sellerPhone: "+213 555 123 456",
    sellerRating: 4.8,
    sellerReviews: 34,
    sellerSince: "2022",
    postedAt: "15 Jan 2024",
    views: 342,
    isBoosted: true,
    isUrgent: false,
  },
  {
    id: "2",
    title: "Appartement F3 à louer – Oran Centre",
    titleAr: "شقة F3 للإيجار – وسط وهران",
    price: 35000,
    negotiable: false,
    category: "real_estate",
    wilaya: "Oran",
    city: "Centre-ville",
    condition: "used",
    description: "Beau F3 de 85m² au 3ème étage avec ascenseur. Proche de tous les commerces. Cuisine équipée, 2 chambres, salon. Disponible immédiatement.",
    descriptionAr: "شقة F3 جميلة بمساحة 85 متر مربع في الطابق الثالث مع مصعد. قريبة من جميع المحلات. مطبخ مجهز، غرفتان، صالون. متاحة فوراً.",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=500&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=500&q=80",
    ],
    sellerId: "u2",
    sellerName: "Nadia Khelifi",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nadia",
    sellerPhone: "+213 661 234 567",
    sellerRating: 4.5,
    sellerReviews: 12,
    sellerSince: "2021",
    postedAt: "14 Jan 2024",
    views: 891,
    isBoosted: true,
    isUrgent: false,
  },
  {
    id: "3",
    title: "Renault Clio 4 – 2019 – 65 000 km",
    titleAr: "رينو كليو 4 – 2019 – 65 ألف كم",
    price: 285000,
    negotiable: true,
    category: "vehicles",
    wilaya: "Constantine",
    city: "El Khroub",
    condition: "used",
    description: "Renault Clio 4 essence, 1.2L, climatisation, vitres électriques. Entretien régulier, carnet de révision à jour. Première main.",
    descriptionAr: "رينو كليو 4 بنزين، 1.2 لتر، تكييف هواء، نوافذ كهربائية. صيانة منتظمة، كتيب المراجعة محدث. مالك أول.",
    images: [
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=500&q=80",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=500&q=80",
    ],
    sellerId: "u3",
    sellerName: "Yacine Amrani",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yacine",
    sellerPhone: "+213 770 345 678",
    sellerRating: 4.9,
    sellerReviews: 67,
    sellerSince: "2020",
    postedAt: "13 Jan 2024",
    views: 1243,
    isBoosted: false,
    isUrgent: true,
  },
  {
    id: "4",
    title: "Samsung 65\" QLED 4K – Neuf déballé",
    titleAr: "سامسونج 65 بوصة QLED 4K – جديد",
    price: 125000,
    negotiable: false,
    category: "electronics",
    wilaya: "Alger",
    city: "Bab Ezzouar",
    condition: "new",
    description: "Télévision Samsung 65\" QLED 4K Smart TV. Acheté mais trop grande pour notre salon. Encore dans la boîte. Garantie 2 ans.",
    descriptionAr: "تلفزيون سامسونج 65 بوصة QLED 4K تلفزيون ذكي. تم شراؤه ولكنه كبير جداً. لا يزال في العلبة. ضمان سنتين.",
    images: [
      "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=500&q=80",
    ],
    sellerId: "u4",
    sellerName: "Sofiane Hadj",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sofiane",
    sellerPhone: "+213 555 456 789",
    sellerRating: 4.2,
    sellerReviews: 8,
    sellerSince: "2023",
    postedAt: "12 Jan 2024",
    views: 567,
    isBoosted: false,
    isUrgent: false,
  },
  {
    id: "5",
    title: "Villa 5 pièces avec jardin – Tizi Ouzou",
    titleAr: "فيلا 5 غرف مع حديقة – تيزي وزو",
    price: 2500000,
    negotiable: true,
    category: "real_estate",
    wilaya: "Tizi Ouzou",
    city: "Tizi Ouzou",
    condition: "used",
    description: "Magnifique villa de 250m² avec grand jardin de 500m². 5 chambres, 3 salles de bain, garage double, piscine.",
    descriptionAr: "فيلا رائعة بمساحة 250 متر مربع مع حديقة كبيرة 500 متر. 5 غرف، 3 حمامات، كراج مزدوج، مسبح.",
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=500&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=500&q=80",
    ],
    sellerId: "u5",
    sellerName: "Melissa Aït Ahmed",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Melissa",
    sellerPhone: "+213 661 567 890",
    sellerRating: 5.0,
    sellerReviews: 5,
    sellerSince: "2023",
    postedAt: "11 Jan 2024",
    views: 2341,
    isBoosted: true,
    isUrgent: false,
  },
  {
    id: "6",
    title: "PlayStation 5 + 3 jeux – Comme neuf",
    titleAr: "بلايستيشن 5 + 3 ألعاب – كالجديد",
    price: 95000,
    negotiable: true,
    category: "electronics",
    wilaya: "Annaba",
    city: "Annaba",
    condition: "used",
    description: "PS5 avec 3 jeux (FIFA 24, God of War, Spider-Man). Très peu utilisé. 2 manettes incluses.",
    descriptionAr: "PS5 مع 3 ألعاب (فيفا 24، قاو أوف وار، سبايدرمان). مستخدم قليلاً. وحدتا تحكم متضمنتان.",
    images: [
      "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=500&q=80",
    ],
    sellerId: "u6",
    sellerName: "Riad Bensalem",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Riad",
    sellerPhone: "+213 770 678 901",
    sellerRating: 4.7,
    sellerReviews: 23,
    sellerSince: "2022",
    postedAt: "10 Jan 2024",
    views: 789,
    isBoosted: false,
    isUrgent: true,
  },
  {
    id: "7",
    title: "MacBook Pro M2 – 512GB – 16GB RAM",
    titleAr: "ماك بوك برو M2 – 512 جيغا – 16 رام",
    price: 210000,
    negotiable: false,
    category: "electronics",
    wilaya: "Alger",
    city: "Kouba",
    condition: "used",
    description: "MacBook Pro 13\" M2, 512GB SSD, 16GB RAM. Acheté il y a 8 mois, parfait état, toujours sous garantie Apple.",
    descriptionAr: "ماك بوك برو 13 بوصة M2، 512 جيغابايت SSD، 16 جيغابايت رام. تم شراؤه قبل 8 أشهر، حالة مثالية.",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&q=80",
    ],
    sellerId: "u1",
    sellerName: "Karim Benali",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Karim",
    sellerPhone: "+213 555 123 456",
    sellerRating: 4.8,
    sellerReviews: 34,
    sellerSince: "2022",
    postedAt: "9 Jan 2024",
    views: 456,
    isBoosted: false,
    isUrgent: false,
  },
  {
    id: "8",
    title: "Canapé d'angle moderne – Très bon état",
    titleAr: "أريكة زاوية عصرية – حالة جيدة جداً",
    price: 45000,
    negotiable: true,
    category: "home_garden",
    wilaya: "Blida",
    city: "Blida",
    condition: "used",
    description: "Grand canapé d'angle en tissu gris anthracite. 6 places, méridienne incluse. Dimensions: 290x200cm.",
    descriptionAr: "أريكة زاوية كبيرة من قماش رمادي غامق. 6 مقاعد، أريكة استلقاء مشمولة. الأبعاد: 290×200 سم.",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&q=80",
    ],
    sellerId: "u7",
    sellerName: "Farida Meziane",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Farida",
    sellerPhone: "+213 555 789 012",
    sellerRating: 4.3,
    sellerReviews: 9,
    sellerSince: "2023",
    postedAt: "8 Jan 2024",
    views: 234,
    isBoosted: false,
    isUrgent: false,
  },
  {
    id: "9",
    title: "Toyota Corolla 2022 – 12 000 km",
    titleAr: "تويوتا كورولا 2022 – 12 ألف كم",
    price: 420000,
    negotiable: true,
    category: "vehicles",
    wilaya: "Sétif",
    city: "Sétif",
    condition: "used",
    description: "Toyota Corolla 2022, automatique, 1.6L, plein options. Comme neuf, première main, carnet à jour.",
    descriptionAr: "تويوتا كورولا 2022، أوتوماتيك، 1.6 لتر، كامل الخيارات. كالجديد، مالك أول.",
    images: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=500&q=80",
    ],
    sellerId: "u8",
    sellerName: "Omar Boudali",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Omar",
    sellerPhone: "+213 661 890 123",
    sellerRating: 4.6,
    sellerReviews: 15,
    sellerSince: "2021",
    postedAt: "7 Jan 2024",
    views: 1567,
    isBoosted: true,
    isUrgent: false,
  },
  {
    id: "10",
    title: "Veste en cuir homme – Taille L",
    titleAr: "جاكيت جلدي رجالي – مقاس L",
    price: 8500,
    negotiable: false,
    category: "clothing",
    wilaya: "Oran",
    city: "Bir El Djir",
    condition: "used",
    description: "Belle veste en cuir véritable, taille L. Achetée en Turquie, portée 3 fois. Couleur marron foncé.",
    descriptionAr: "جاكيت جلد طبيعي جميل، مقاس L. تم شراؤه في تركيا، مرتدى 3 مرات. لون بني غامق.",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&q=80",
    ],
    sellerId: "u9",
    sellerName: "Hamza Lakhdar",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hamza",
    sellerPhone: "+213 770 901 234",
    sellerRating: 4.1,
    sellerReviews: 6,
    sellerSince: "2023",
    postedAt: "6 Jan 2024",
    views: 123,
    isBoosted: false,
    isUrgent: false,
  },
  {
    id: "11",
    title: "Terrain agricole 1 ha – Biskra",
    titleAr: "أرض فلاحية هكتار واحد – بسكرة",
    price: 1800000,
    negotiable: true,
    category: "real_estate",
    wilaya: "Biskra",
    city: "Biskra",
    condition: "used",
    description: "Terrain agricole de 1 hectare avec puits artésien. Idéal pour palmiers dattiers ou maraîchage.",
    descriptionAr: "أرض فلاحية مساحتها هكتار واحد مع بئر ارتوازي. مثالية لزراعة النخيل.",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=500&q=80",
    ],
    sellerId: "u10",
    sellerName: "Abdelkader Sahraoui",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Abdelkader",
    sellerPhone: "+213 555 012 345",
    sellerRating: 4.4,
    sellerReviews: 3,
    sellerSince: "2023",
    postedAt: "5 Jan 2024",
    views: 678,
    isBoosted: false,
    isUrgent: false,
  },
  {
    id: "12",
    title: "Développeur Web Full-Stack – CDI Alger",
    titleAr: "مطور ويب – دوام كامل الجزائر",
    price: 80000,
    negotiable: false,
    category: "jobs",
    wilaya: "Alger",
    city: "Alger Centre",
    condition: "new",
    description: "Startup tech recherche développeur full-stack (React/Node). 2+ ans expérience. Salaire compétitif + avantages.",
    descriptionAr: "شركة ناشئة تبحث عن مطور full-stack (React/Node). خبرة 2+ سنوات. راتب تنافسي + مزايا.",
    images: [
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=500&q=80",
    ],
    sellerId: "u11",
    sellerName: "TechAlgeria DZ",
    sellerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=TechAlgeria",
    sellerPhone: "+213 661 123 456",
    sellerRating: 4.9,
    sellerReviews: 42,
    sellerSince: "2020",
    postedAt: "4 Jan 2024",
    views: 2890,
    isBoosted: true,
    isUrgent: false,
  },
];

export const CONVERSATIONS: Conversation[] = [
  {
    id: "c1",
    listingId: "1",
    listingTitle: "iPhone 14 Pro 256GB",
    listingImage: "https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=100&q=80",
    otherUser: { id: "u1", name: "Karim Benali", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Karim" },
    lastMessage: "Est-ce que le prix est ferme ?",
    lastMessageTime: "14:23",
    unread: 2,
    messages: [
      { id: "m1", senderId: "me", text: "Bonjour, est-ce que l'iPhone est encore disponible ?", time: "14:00" },
      { id: "m2", senderId: "u1", text: "Oui, il est toujours disponible ! Vous êtes intéressé ?", time: "14:15" },
      { id: "m3", senderId: "me", text: "Est-ce que le prix est ferme ?", time: "14:23" },
    ],
  },
  {
    id: "c2",
    listingId: "3",
    listingTitle: "Renault Clio 4",
    listingImage: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=100&q=80",
    otherUser: { id: "u3", name: "Yacine Amrani", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yacine" },
    lastMessage: "On peut faire 275 000 DA, pas moins.",
    lastMessageTime: "Hier",
    unread: 0,
    messages: [
      { id: "m4", senderId: "u3", text: "Bonjour, vous êtes intéressé par la Clio ?", time: "Hier 10:00" },
      { id: "m5", senderId: "me", text: "Oui ! Vous pouvez faire un meilleur prix ?", time: "Hier 10:30" },
      { id: "m6", senderId: "u3", text: "On peut faire 275 000 DA, pas moins.", time: "Hier 11:00" },
    ],
  },
  {
    id: "c3",
    listingId: "5",
    listingTitle: "Villa 5 pièces",
    listingImage: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=100&q=80",
    otherUser: { id: "u5", name: "Melissa Aït Ahmed", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Melissa" },
    lastMessage: "La villa est toujours disponible pour visite.",
    lastMessageTime: "Lun",
    unread: 1,
    messages: [
      { id: "m7", senderId: "me", text: "Bonjour, je voudrais visiter la villa.", time: "Lun 09:00" },
      { id: "m8", senderId: "u5", text: "La villa est toujours disponible pour visite.", time: "Lun 09:45" },
    ],
  },
];
